-- +goose Up

CREATE TABLE users (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      text        NOT NULL,
    email         text,
    password_hash text        NOT NULL,
    role          text        NOT NULL DEFAULT 'reader'
                              CHECK (role IN ('admin','editor','reader')),
    is_active     boolean     NOT NULL DEFAULT true,
    locale        text        NOT NULL DEFAULT 'en',
    created_at    timestamptz NOT NULL DEFAULT now(),
    updated_at    timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX users_username_key ON users (lower(username));
CREATE UNIQUE INDEX users_email_key    ON users (lower(email)) WHERE email IS NOT NULL;

-- Session store for alexedwards/scs.
CREATE TABLE sessions (
    token  text        PRIMARY KEY,
    data   bytea       NOT NULL,
    expiry timestamptz NOT NULL
);
CREATE INDEX sessions_expiry_idx ON sessions (expiry);

-- ---------------------------------------------------------------------------
-- Shelves. A shelf with kobo_sync = true is what the device sees as a
-- Collection, and is the ONLY set of books a sync request ever looks at.
-- ---------------------------------------------------------------------------

CREATE TABLE shelves (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid       uuid        NOT NULL DEFAULT gen_random_uuid(),
    user_id    bigint      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    name       text        NOT NULL,
    is_public  boolean     NOT NULL DEFAULT false,
    kobo_sync  boolean     NOT NULL DEFAULT false,
    position   int         NOT NULL DEFAULT 0,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX shelves_uuid_key      ON shelves (uuid);
CREATE UNIQUE INDEX shelves_user_name_key ON shelves (user_id, lower(name));
CREATE INDEX shelves_kobo_idx  ON shelves (user_id, updated_at) WHERE kobo_sync;

CREATE TABLE shelf_books (
    shelf_id bigint      NOT NULL REFERENCES shelves (id) ON DELETE CASCADE,
    book_id  bigint      NOT NULL REFERENCES books   (id) ON DELETE CASCADE,
    position int         NOT NULL DEFAULT 0,
    added_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (shelf_id, book_id)
);
-- Drives the shelf-scoped sync query; ordering matches its ORDER BY.
CREATE INDEX shelf_books_sync_idx ON shelf_books (shelf_id, added_at, book_id);
CREATE INDEX shelf_books_book_idx ON shelf_books (book_id);

-- Tombstones. Without these a device can never learn that something went away:
-- the row it needs to hear about no longer exists to be selected.
CREATE TABLE shelf_book_removals (
    shelf_id   bigint      NOT NULL,
    book_id    bigint      NOT NULL,
    user_id    bigint      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    removed_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (shelf_id, book_id)
);
CREATE INDEX shelf_book_removals_sync_idx ON shelf_book_removals (user_id, removed_at);

CREATE TABLE deleted_shelves (
    uuid       uuid        PRIMARY KEY,
    user_id    bigint      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    deleted_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX deleted_shelves_sync_idx ON deleted_shelves (user_id, deleted_at);

-- ---------------------------------------------------------------------------
-- Kobo device auth + state
-- ---------------------------------------------------------------------------

-- calibre-web's model: a random token embedded in the URL path the device is
-- configured with. There is no cookie and no OAuth handshake.
CREATE TABLE kobo_auth_tokens (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      bigint      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    token        text        NOT NULL,
    label        text        NOT NULL DEFAULT '',
    created_at   timestamptz NOT NULL DEFAULT now(),
    last_used_at timestamptz
);
CREATE UNIQUE INDEX kobo_auth_tokens_token_key ON kobo_auth_tokens (token);
CREATE INDEX kobo_auth_tokens_user_idx ON kobo_auth_tokens (user_id);

CREATE TABLE kobo_devices (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      bigint      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    device_id    text        NOT NULL,
    model        text        NOT NULL DEFAULT '',
    firmware     text        NOT NULL DEFAULT '',
    first_seen_at timestamptz NOT NULL DEFAULT now(),
    last_sync_at timestamptz
);
CREATE UNIQUE INDEX kobo_devices_key ON kobo_devices (user_id, device_id);

-- Mirrors Kobo's ReadingState: StatusInfo + Statistics + CurrentBookmark.
CREATE TABLE reading_state (
    user_id  bigint NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    book_id  bigint NOT NULL REFERENCES books (id) ON DELETE CASCADE,

    status   text   NOT NULL DEFAULT 'ReadyToRead'
                    CHECK (status IN ('ReadyToRead','Reading','Finished')),

    progress_percent                int,
    content_source_progress_percent int,
    location_value                  text,
    location_type                   text,
    location_source                 text,

    spent_reading_minutes  int,
    remaining_time_minutes int,

    times_started_reading     int NOT NULL DEFAULT 0,
    last_time_started_reading timestamptz,
    last_time_finished        timestamptz,

    priority_timestamp timestamptz NOT NULL DEFAULT now(),
    last_modified      timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id, book_id)
);
CREATE INDEX reading_state_sync_idx ON reading_state (user_id, last_modified, book_id);

-- What we have already told this device about, so NewEntitlement vs
-- ChangedEntitlement is a fact rather than an inference from timestamps.
CREATE TABLE kobo_synced_books (
    user_id         bigint      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    book_id         bigint      NOT NULL REFERENCES books (id) ON DELETE CASCADE,
    first_synced_at timestamptz NOT NULL DEFAULT now(),
    last_synced_at  timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id, book_id)
);

CREATE TABLE kobo_archived (
    user_id     bigint      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    book_id     bigint      NOT NULL REFERENCES books (id) ON DELETE CASCADE,
    archived_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id, book_id)
);
CREATE INDEX kobo_archived_sync_idx ON kobo_archived (user_id, archived_at);

-- +goose Down
DROP TABLE IF EXISTS kobo_archived, kobo_synced_books, reading_state, kobo_devices,
                     kobo_auth_tokens, deleted_shelves, shelf_book_removals,
                     shelf_books, shelves, sessions, users CASCADE;
