-- +goose Up

-- ---------------------------------------------------------------------------
-- Reference entities
-- ---------------------------------------------------------------------------

CREATE TABLE authors (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       text        NOT NULL COLLATE library_sort,
    sort       text        NOT NULL DEFAULT '' COLLATE library_sort,
    link       text        NOT NULL DEFAULT '',
    created_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX authors_name_key  ON authors (name);
CREATE        INDEX authors_sort_idx  ON authors (sort, id);
CREATE        INDEX authors_name_trgm ON authors USING gin (f_unaccent(name) gin_trgm_ops);

CREATE TABLE series (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       text        NOT NULL COLLATE library_sort,
    sort       text        NOT NULL DEFAULT '' COLLATE library_sort,
    created_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX series_name_key  ON series (name);
CREATE        INDEX series_sort_idx  ON series (sort, id);
CREATE        INDEX series_name_trgm ON series USING gin (f_unaccent(name) gin_trgm_ops);

CREATE TABLE publishers (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       text        NOT NULL COLLATE library_sort,
    created_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX publishers_name_key ON publishers (name);

CREATE TABLE tags (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       text        NOT NULL COLLATE library_sort,
    created_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX tags_name_key  ON tags (name);
CREATE        INDEX tags_name_trgm ON tags USING gin (f_unaccent(name) gin_trgm_ops);

-- ---------------------------------------------------------------------------
-- books
--
-- Normalised for correctness (link tables below), denormalised for reads: the
-- author_names / tag_names / series_name / *_flat columns are maintained by the
-- triggers at the bottom of this file. This is the single most important
-- departure from calibre-web -- it lets the grid query hit one table with no
-- joins, instead of fanning out per row.
-- ---------------------------------------------------------------------------

CREATE TABLE books (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Carried verbatim from Calibre so existing Kobo entitlements keep working.
    uuid          uuid        NOT NULL,
    calibre_id    bigint,

    title         text        NOT NULL COLLATE library_sort,
    title_sort    text        NOT NULL DEFAULT '' COLLATE library_sort,
    description   text,
    series_id     bigint      REFERENCES series (id)     ON DELETE SET NULL,
    series_index  numeric(10,2),
    publisher_id  bigint      REFERENCES publishers (id) ON DELETE SET NULL,
    pubdate       date,
    -- Calibre stores rating 0-10 (half stars).
    rating        smallint    CHECK (rating IS NULL OR rating BETWEEN 0 AND 10),
    languages     text[]      NOT NULL DEFAULT '{}',

    -- Directory holding this book's files, relative to the library root.
    path          text        NOT NULL,
    has_cover     boolean     NOT NULL DEFAULT false,

    custom        jsonb       NOT NULL DEFAULT '{}',
    needs_review  boolean     NOT NULL DEFAULT false,

    added_at      timestamptz NOT NULL DEFAULT now(),
    -- Bumped by trigger on every write; drives Kobo incremental sync.
    updated_at    timestamptz NOT NULL DEFAULT now(),

    -- ---- denormalised read path (trigger-maintained, do not write directly) ----
    author_names  text[]      NOT NULL DEFAULT '{}',
    author_sort   text        NOT NULL DEFAULT '' COLLATE library_sort,
    authors_flat  text        NOT NULL DEFAULT '',
    tag_names     text[]      NOT NULL DEFAULT '{}',
    tags_flat     text        NOT NULL DEFAULT '',
    series_name   text COLLATE library_sort,

    search_tsv tsvector GENERATED ALWAYS AS (
        setweight(to_tsvector('library_search', f_unaccent(coalesce(title,        ''))), 'A') ||
        setweight(to_tsvector('library_search', f_unaccent(coalesce(authors_flat, ''))), 'B') ||
        setweight(to_tsvector('library_search', f_unaccent(coalesce(series_name,  ''))), 'C') ||
        setweight(to_tsvector('library_search', f_unaccent(coalesce(tags_flat,    ''))), 'D')
    ) STORED
);

CREATE UNIQUE INDEX books_uuid_key       ON books (uuid);
CREATE UNIQUE INDEX books_calibre_id_key ON books (calibre_id) WHERE calibre_id IS NOT NULL;

-- Keyset pagination sorts. Each is (sort_key, id) so the cursor is total-ordered.
CREATE INDEX books_title_sort_idx  ON books (title_sort, id);
CREATE INDEX books_added_idx       ON books (added_at DESC, id DESC);
CREATE INDEX books_updated_idx     ON books (updated_at, id);
CREATE INDEX books_author_sort_idx ON books (author_sort, series_index NULLS FIRST, title_sort, id);
CREATE INDEX books_series_idx      ON books (series_id, series_index, id) WHERE series_id IS NOT NULL;
CREATE INDEX books_rating_idx      ON books (rating DESC NULLS LAST, id) WHERE rating IS NOT NULL;
CREATE INDEX books_needs_review_idx ON books (id) WHERE needs_review;

-- Search.
CREATE INDEX books_search_idx      ON books USING gin (search_tsv);
CREATE INDEX books_title_trgm      ON books USING gin (f_unaccent(title) gin_trgm_ops);
CREATE INDEX books_authors_trgm    ON books USING gin (f_unaccent(authors_flat) gin_trgm_ops);

-- Facet filtering straight off the denormalised arrays.
CREATE INDEX books_author_names_idx ON books USING gin (author_names);
CREATE INDEX books_tag_names_idx    ON books USING gin (tag_names);
CREATE INDEX books_languages_idx    ON books USING gin (languages);
CREATE INDEX books_custom_idx       ON books USING gin (custom jsonb_path_ops);

-- ---------------------------------------------------------------------------
-- Link tables
-- ---------------------------------------------------------------------------

CREATE TABLE book_authors (
    book_id   bigint NOT NULL REFERENCES books   (id) ON DELETE CASCADE,
    author_id bigint NOT NULL REFERENCES authors (id) ON DELETE CASCADE,
    position  int    NOT NULL DEFAULT 0,
    PRIMARY KEY (book_id, author_id)
);
CREATE INDEX book_authors_author_idx ON book_authors (author_id, book_id);

CREATE TABLE book_tags (
    book_id bigint NOT NULL REFERENCES books (id) ON DELETE CASCADE,
    tag_id  bigint NOT NULL REFERENCES tags  (id) ON DELETE CASCADE,
    PRIMARY KEY (book_id, tag_id)
);
CREATE INDEX book_tags_tag_idx ON book_tags (tag_id, book_id);

CREATE TABLE identifiers (
    book_id bigint NOT NULL REFERENCES books (id) ON DELETE CASCADE,
    scheme  text   NOT NULL,   -- isbn, amazon, goodreads, google, ...
    value   text   NOT NULL,
    PRIMARY KEY (book_id, scheme)
);
CREATE INDEX identifiers_lookup_idx ON identifiers (scheme, value);

-- One row per physical file on disk.
CREATE TABLE book_files (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id    bigint      NOT NULL REFERENCES books (id) ON DELETE CASCADE,
    format     text        NOT NULL,   -- uppercase: EPUB, PDF, MOBI, KEPUB
    filename   text        NOT NULL,   -- basename within books.path
    size_bytes bigint      NOT NULL DEFAULT 0,
    sha256     bytea,
    added_at   timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX book_files_book_format_key ON book_files (book_id, format);
-- Ingest dedupe: recognise a file we already hold, wherever it was dropped.
CREATE INDEX book_files_sha256_idx ON book_files (sha256) WHERE sha256 IS NOT NULL;

-- +goose Down
DROP TABLE IF EXISTS book_files, identifiers, book_tags, book_authors, books,
                     tags, publishers, series, authors CASCADE;
