-- +goose Up

-- ---------------------------------------------------------------------------
-- Journal for the managed file tree.
--
-- Every move/copy/delete is written here as an intent BEFORE the filesystem is
-- touched, and marked done in the same transaction that updates books.path.
-- On startup the reconciler replays every row that is not 'done', so a crash
-- mid-move can never leave the database and the filesystem disagreeing.
-- ---------------------------------------------------------------------------

CREATE TABLE file_operations (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id      bigint      REFERENCES books (id) ON DELETE SET NULL,
    op           text        NOT NULL CHECK (op IN ('move','copy','delete','mkdir','rmdir')),
    src          text        NOT NULL DEFAULT '',
    dst          text        NOT NULL DEFAULT '',
    -- Expected content hash of src, verified at dst before src is unlinked.
    sha256       bytea,
    size_bytes   bigint,
    state        text        NOT NULL DEFAULT 'pending'
                             CHECK (state IN ('pending','staged','done','failed')),
    attempts     int         NOT NULL DEFAULT 0,
    error        text        NOT NULL DEFAULT '',
    created_at   timestamptz NOT NULL DEFAULT now(),
    completed_at timestamptz
);

-- The reconciler's scan on boot: only unfinished work, newest last.
CREATE INDEX file_operations_open_idx ON file_operations (created_at, id)
    WHERE state IN ('pending','staged');
CREATE INDEX file_operations_book_idx ON file_operations (book_id, created_at DESC);
CREATE INDEX file_operations_failed_idx ON file_operations (created_at DESC)
    WHERE state = 'failed';

-- +goose Down
DROP TABLE IF EXISTS file_operations;
