-- +goose Up

-- Durable background work queue.
--
-- Deliberately hand-rolled rather than pulling in a queue library: the whole
-- contract is "claim one row, do the work, mark it done", SELECT ... FOR UPDATE
-- SKIP LOCKED gives that safely across workers, and owning it means the retry
-- and dedupe semantics are visible in this file rather than in a dependency.
CREATE TABLE jobs (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind         text        NOT NULL,
    -- Identifies the thing being worked on, so the same work is never queued
    -- twice while it is still pending.
    dedupe_key   text        NOT NULL,
    payload      jsonb       NOT NULL DEFAULT '{}',
    priority     int         NOT NULL DEFAULT 100,
    state        text        NOT NULL DEFAULT 'pending'
                             CHECK (state IN ('pending','running','done','failed')),
    attempts     int         NOT NULL DEFAULT 0,
    max_attempts int         NOT NULL DEFAULT 5,
    last_error   text        NOT NULL DEFAULT '',
    run_after    timestamptz NOT NULL DEFAULT now(),
    locked_at    timestamptz,
    locked_by    text,
    created_at   timestamptz NOT NULL DEFAULT now(),
    finished_at  timestamptz
);

-- One outstanding job per (kind, target). Completed rows are excluded so the
-- same work can be queued again later -- a book re-converted after an edit.
CREATE UNIQUE INDEX jobs_dedupe_idx ON jobs (kind, dedupe_key)
    WHERE state IN ('pending','running');

-- The claim query's access path.
CREATE INDEX jobs_claim_idx ON jobs (kind, priority, run_after, id)
    WHERE state = 'pending';
CREATE INDEX jobs_state_idx ON jobs (state, finished_at DESC);
-- Reclaiming jobs abandoned by a crashed worker.
CREATE INDEX jobs_stuck_idx ON jobs (locked_at) WHERE state = 'running';

-- +goose Down
DROP TABLE IF EXISTS jobs;
